version: '3'

services:
  coffee-shop-api:
    build:
      context: .
      dockerfile: CoffeeShopApiDockerfile
    ports:
      - "5000:80"
  coffee-shop-coordinator:
    build:
      context: .
      dockerfile: CoffeeShopCoordinatorDockerfile
  coffee-shop-saga:
    build:
      context: .
      dockerfile: CoffeeShopSagaDockerfile
  barista-coordinator:
    build:
      context: .
      dockerfile: BaristaCoordinatorDockerfile
  barista-api:
    build:
      context: .
      dockerfile: BaristaApiDockerfile
    ports:
      - "5001:80"
