version: '3'

services:
  coffee-shop-web:
    build:
      context: .
      dockerfile: CoffeeShopWebDockerfile
    ports:
      - "5010:80"
  coffee-shop-api:
    build:
      context: .
      dockerfile: CoffeeShopApiDockerfile
    ports:
      - "5000:80"
  coffee-shop-coordinator:
    build:
      context: .
      dockerfile: CoffeeShopCoordinatorDockerfile
  coffee-shop-saga:
    build:
      context: .
      dockerfile: CoffeeShopSagaDockerfile

  barista-web:
    build:
      context: .
      dockerfile: BaristaWebDockerfile
    ports:
      - "5011:80"
  barista-coordinator:
    build:
      context: .
      dockerfile: BaristaCoordinatorDockerfile
  barista-api:
    build:
      context: .
      dockerfile: BaristaApiDockerfile
    ports:
      - "5001:80"

  bakery-web:
    build:
      context: .
      dockerfile: BakeryWebDockerfile
    ports:
      - "5012:80"
  bakery-coordinator:
    build:
      context: .
      dockerfile: BakeryCoordinatorDockerfile
  bakery-api:
    build:
      context: .
      dockerfile: BakeryApiDockerfile
    ports:
      - "5002:80"
