version: '3'

services:
  rabbit:
    image: "rabbitmq:management-alpine"
    environment:
      - RABBITMQ_DEFAULT_USER=phil
      - RABBITMQ_DEFAULT_PASS=likesBagels
    ports:
      - "5672:5672"
      - "15672:15672"
  coffee-shop-db:
    build:
      context: .
      dockerfile: CoffeeShopDbDockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=coffeeShopOwner!@
    ports:
      - "1433:1433"